dateModified: 1743784056
email:
  fromEmail: msmith@phase2.io
  fromName: testing
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6b4818bc-88c3-4586-96f0-866ec1ae3d51: testing # testing
    e008e1fb-da53-41a0-9793-a0de8082d504: testing # testing
system:
  edition: solo
  live: true
  name: testing
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
